#!/bin/bash
#
#   Copyright (C) 2014-15 Chris Copsey
#
#   This file is part of ccFOAM.
#
#   ccFOAM is free software: you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#
#   ccFOAM is distributed in the hope that it will be useful, but WITHOUT ANY
#   WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
#   details.
#
#   You should have received a copy of the GNU General Public License along
#   with ccFOAM.  If not, see <http://www.gnu.org/licenses/>.
#

language: cpp

compiler:
  - gcc
  - clang

sudo: false

cache:
  directories:
    - $HOME/.ccache

env:
  - TARGET="pisoFoam blockMesh libsampling libfieldFunctionObjects"
  - TARGET="all"

addons:
  apt:
    packages:
    - libboost-system-dev
    - libboost-thread-dev
    - libgmp-dev
    - libopenmpi-dev
    - libmpfr-dev

before_install:
  - export PATH=/usr/lib/ccache:$PATH

install:
  - ./ccfoam/buildscripts/parmgridgen-1.0-travis
  - ./ccfoam/buildscripts/CGAL-4.5-travis
  - ./ccfoam/buildscripts/metis-5.1.0-travis
  - ./ccfoam/buildscripts/parmetis-4.0.3-travis
  - ./ccfoam/buildscripts/scotch-6.0.4-travis

script:
  - ./ccfoam/buildscripts/ccFOAM-dev-travis

matrix:
  exclude:
    - compiler: clang
      env: TARGET="pisoFoam blockMesh libsampling libfieldFunctionObjects"
  allow_failures:
    - compiler: gcc
      env: TARGET="all"
  fast_finish: true
