#!/bin/bash
#
#   Copyright (C) 2014-15 Chris Copsey
#
#   This file is part of ccFOAM.
#
#   ccFOAM is free software: you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#
#   ccFOAM is distributed in the hope that it will be useful, but WITHOUT ANY
#   WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
#   details.
#
#   You should have received a copy of the GNU General Public License along
#   with ccFOAM.  If not, see <http://www.gnu.org/licenses/>.
#

SRC_PATH=`pwd`
BUILD_PATH=${HOME}/build
#GRAPHVIZ="--graphviz=${HOME}/graphviz"
DEPS_PATH="${HOME}/dependencies"

mkdir -p ${BUILD_PATH}
cd ${BUILD_PATH}

cmake ${GRAPHVIZ} ${SRC_PATH} \
  -DBUILD_SHARED_LIBS=ON \
  -DCMAKE_CXX_FLAGS="-w" \
  -DMGRIDGEN_ROOT=${DEPS_PATH}/parmgridgen-1.0-install \
  -DPARMGRIDGEN_ROOT=${DEPS_PATH}/parmgridgen-1.0-install

#cat ${GRAPHVIZ_PATH}

make libOpenFOAM
