#
#   Copyright (C) 2014-15 Chris Copsey
#   
#   This file is part of ccFOAM.
#
#   ccFOAM is free software: you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#
#   ccFOAM is distributed in the hope that it will be useful, but WITHOUT ANY
#   WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
#   details.
#
#   You should have received a copy of the GNU General Public License along
#   with ccFOAM.  If not, see <http://www.gnu.org/licenses/>.
#

include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/algorithms/MeshWave)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/algorithms/PatchEdgeFaceWave)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/algorithms/PointEdgeWave)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/AMIInterpolation)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/AMIMethod)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/directAMI)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/faceAreaWeightAMI)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/mapNearestAMI)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/partialFaceAreaWeightAMI)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/faceAreaIntersect)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/GAMG/interfaceFields/cyclicACMIGAMGInterfaceField)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/GAMG/interfaceFields/cyclicAMIGAMGInterfaceField)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/GAMG/interfaces/cyclicACMIGAMGInterface)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/GAMG/interfaces/cyclicAMIGAMGInterface)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMILduInterfaceField)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPointPatch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPointPatchField)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPolyPatch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMILduInterfaceField)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatchField)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/cellClassification)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/cellDist)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/cellDist/patchWave)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/cellDist/wallPoint)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/cellFeatures)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/cellQuality)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/coordinateSystems)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/coordinateSystems/coordinateRotation)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/edgeFaceCirculator)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/indexedOctree)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/mappedPatches/mappedPointPatch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/mappedPatches/mappedPolyPatch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/meshSearch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/meshStructure)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/meshTools)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/momentOfInertia)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/polyMeshZipUpCells)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/primitiveMeshGeometry)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/regionCoupled/GAMG/interfaceFields/regionCoupledGAMGInterfaceField)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/regionCoupled/GAMG/interfaces/regionCoupledGAMGInterface)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/regionCoupled/patches/regionCoupledLduInterface)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/regionCoupled/patches/regionCoupledPointPatch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/regionCoupled/patches/regionCoupledPolyPatch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/regionSplit)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/searchableSurface)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/boxToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/cellToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/cylinderAnnulusToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/cylinderToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/faceToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/faceZoneToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/fieldToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/labelToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/nbrToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/nearestToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/pointToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/regionToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/rotatedBoxToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/shapeToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/sphereToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/surfaceToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/targetVolumeToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellSources/zoneToCell)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/cellZoneSources/setToCellZone)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/boundaryToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/boxToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/cellToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/faceToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/labelToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/normalToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/patchToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/pointToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/regionToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceSources/zoneToFace)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceZoneSources/faceZoneToFaceZone)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceZoneSources/searchableSurfaceToFaceZone)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceZoneSources/setAndNormalToFaceZone)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceZoneSources/setsToFaceZone)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/faceZoneSources/setToFaceZone)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/pointSources/boxToPoint)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/pointSources/cellToPoint)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/pointSources/faceToPoint)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/pointSources/labelToPoint)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/pointSources/nearestToPoint)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/pointSources/pointToPoint)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/pointSources/surfaceToPoint)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/pointSources/zoneToPoint)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/pointZoneSources/setToPointZone)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/topoSets)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/sets/topoSetSource)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/surfaceSets)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/tetOverlapVolume)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/booleanOps/booleanSurface)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/booleanOps/intersectedSurface)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/booleanOps/surfaceIntersection)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/orientedSurface)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/surfaceFeatures)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/surfaceLocation)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/triangleFuncs)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/triSurfaceSearch)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/triSurfaceTools)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/triSurface/triSurfaceTools/geompack)
include_directories(${PROJECT_SOURCE_DIR}/src/meshTools/twoDPointCorrector)
